name: Execute Lambda Deploy Script

on:
  push:
    tags:
      - 'v*'
      - 'V*'
    branches:
      - develop
      - main
      - qa
    paths-ignore:
      - 'README.md'
      

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Run Shell Script
      if: |
        contains(github.event_name, 'push') &&
        contains(github.event_name, 'tags') &&
        (contains(github.ref, 'refs/heads/develop') || contains(github.ref, 'refs/heads/qa') || contains(github.ref, 'refs/heads/main'))
      run: |
        chmod +x ga.sh
        sh ga.sh
